### ISSUE TITLE
Use SAML2 / OAuth 2.0 in same client and System

### ISSUE THREAD

**Issue by sweiDl** [MartinPankraz/SAP-MSTeams-Hero#1]
Hi @MartinPankraz,

first thanks for the great explanation and the How-To Video for Hitchhiker 103a. I successfully managed to receive an token when only using Principal Propagation via OAuth 2.0..

However, a more common scenario in my opinion would be that the system supports both (normal SAML2 SSO for FLP f.e. and the PrincipalPropagation for OAuth 2.0)

I tried this approach by adding an additional "Identity Provider" in the SAML2 Configuration. But as soon as I add this one and activate it, the OAuth fails because of  "Exception was Attribute 'Recipient' of element 'SubjectConfirmationData' is invalid".

Is there any way or additional config to do when I want to use both mechanisms?

Thanks and best regards,
Sascha

**Comment by sweiDl** [comment]
Nevermind. Sorry was an caching issue.

**Comment by MartinPankraz** [comment]
@sweiDl great to hear you were able to resolve! Would you mind sharing your config in high level words for the community to pick up if they have similar challenges? 

It is important to use the flags on Azure AD enterprise app registration the right way to support SAML and OAuth in parallel.

I expect you put sth like this?

![image](https://user-images.githubusercontent.com/5108923/231166863-dbf0248a-c410-4cd2-9b30-3ab992fec2c5.png)

KR
Martin

**Comment by sweiDl** [comment]
Hey @MartinPankraz,

sure.. here's what we did:

Basically we just added the second reply URL for the normal SAML2.0 endpoint inside the Azure Configuration. 
<img width="829" alt="image" src="https://user-images.githubusercontent.com/111108662/231711988-61666b0a-9eef-4938-ad88-a38edd11c9ba.png">

On SAP Side it was important that we changed the Assertion Consumption Service inside the SAML2 Provider to the ACS URL:
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/111108662/231713782-a76dc323-650f-4f8b-abf2-ae52b44f3ea8.png">


with those two additional steps we were able to follow your guide and implement both oauth2 and saml2 on the same system and client.

**Comment by NiklasJegg1** [comment]
HI @sweiDl where exactly in the SAP system did you change this? i have the exact opposite case where saml 2 was configured before and i need to add oauth :)`{
    "error": "invalid_grant",
    "error_description": "Angegebene Berechtigungserteilung ist ungültig. Ausnahme war Entität http://TSA100 ist nicht im Element 'AudienceRestriction' definiert. Weitere Informationen in Kernel-Traces oder SAP-Hinweis 1688545 (OAuth-2.0-Fehlerbehebung)"
}`

did you get a similar error?

**Comment by MartinPankraz** [comment]
> HI [@sweiDl](https://github.com/sweiDl) where exactly in the SAP system did you change this? i have the exact opposite case where saml 2 was configured before and i need to add oauth :)`{ "error": "invalid_grant", "error_description": "Angegebene Berechtigungserteilung ist ungültig. Ausnahme war Entität http://TSA100 ist nicht im Element 'AudienceRestriction' definiert. Weitere Informationen in Kernel-Traces oder SAP-Hinweis 1688545 (OAuth-2.0-Fehlerbehebung)" }`
> 
> did you get a similar error?

Hi @NiklasJegg1 you would still need the same sequence that @sweiDl has in above screenshot. Let the community know if you figured it out :-)

**Comment by NiklasJegg1** [comment]
Hi @MartinPankraz i have figured it out :=)

I have just created a second Enterprise Application with the oAuth ACS. Then i downloaded the metadata and created the oAuth service in SAP.

For now this is working in the Test System. But how dou you handle multiple API´s ? 

![Image](https://github.com/user-attachments/assets/b41c2252-29c4-4105-bae3-835d3a626cfc)

The Debug in 103b is working just fine for my initial setup. I just dont get the API Scope´s and multiple/ different APi´s.

e.g. the API_RFQ_PROCESS_SRV is working but the MMIM_MATERIAL_DATA_SRV is not. Do i need to hardcode the {{SAPOAuthScope}} in the APIM Policies?

Thanks a lot for a way to connect to sap i have beed looking for one every other year :D

**Comment by MartinPankraz** [comment]
> Hi @MartinPankraz i have figured it out :=)
> 
> I have just created a second Enterprise Application with the oAuth ACS. Then i downloaded the metadata and created the oAuth service in SAP.
> 
> For now this is working in the Test System. But how dou you handle multiple API´s ? 
> 
> ![Image](https://github.com/user-attachments/assets/b41c2252-29c4-4105-bae3-835d3a626cfc)
> 
> The Debug in 103b is working just fine for my initial setup. I just dont get the API Scope´s and multiple/ different APi´s.
> 
> e.g. the API_RFQ_PROCESS_SRV is working but the MMIM_MATERIAL_DATA_SRV is not. Do i need to hardcode the {{SAPOAuthScope}} in the APIM Policies?
> 
> Thanks a lot for a way to connect to sap i have beed looking for one every other year :D

Nice. Answer to your question is twofold.
 
1. A single oauth client can have multiple scopes. Maintain them space separated on the named value for {{SAPOAuthScope}}. That would be a one client fits all approach diminishing security a bit in favor of governance.

2. Create multiple oauth clients and scope assignments as most secure but high governance. The policy would require slight enhancement for that. For instance Prefix the named values with API Name. Also consider devops approach and APIM ARM apis to create this at scale for hundreds of APIs and OAuth clients.

I will consider enhancing the policy template to cater for that but I feel it goes beyond the blueprint idea.

Thoughts?

**Comment by NiklasJegg1** [comment]
@MartinPankraz  aaah i think i get it. so the scope´s in postman like this? 

![Image](https://github.com/user-attachments/assets/de20922a-509b-4c53-9508-42f4e0ae33dc)

this gives me the token in debug with     "scope": "ZAPI_RFQ_PROCESS_SRV_0001 ZMD_PRODUCT_OP_SRV_0001 ZMMIM_MATERIAL_DATA_SRV_0001"

However it is still behaving weird - maybe sap permissions?
eg. the sap/opu/odata/sap/API_RFQ_PROCESS_SRV/A_RequestForQuotation is giving me 401 

![Image](https://github.com/user-attachments/assets/c4f02faf-761e-4693-aa9b-b0d33953ca9c)

but the Debug call backend service fia vnet is working fine and also sap/opu/odata/sap/API_RFQ_PROCESS_SRV/$metadata is working fine on 103b 2 Call OData backend service on SAP via APIM.

Named Value here: 

![Image](https://github.com/user-attachments/assets/e2b7c987-2592-4e36-9fb7-f5c99b27fcdb)

I think its fine as it is :) maybe just a little hint about the multiple scopes or maybe i missed something.

**Comment by MartinPankraz** [comment]
Almost yes. But is the oauth client in SAP also equipped with the multiple scopes? Transaction SOAUTH2 to start the webdynpro to maintain.

**Comment by NiklasJegg1** [comment]
@MartinPankraz it is yes 

![Image](https://github.com/user-attachments/assets/3718f5f1-2284-45fc-ad48-23389fd31e6b)

**Comment by NiklasJegg1** [comment]
@MartinPankraz  i have no clue how but it is working now. i have not changed a thing 

![Image](https://github.com/user-attachments/assets/bb2e8d73-ca1f-4188-bcdd-aaf0fdcfafe0)

**Comment by MartinPankraz** [comment]
Be aware of timing till changes are active and watch out for the token caching on the policy. Consider dropping the caching when you make token changes. Otherwise, you may be stuck with an older token not reflecting your change.

Cookies on Postman can also be a challenge.

**Comment by NiklasJegg1** [comment]
@MartinPankraz  okay thanks a lot i will keep that in mind. Fyi i have added the SAP OData Power platform connector in the Expose in API section for the Middle tier. This also works quite well in Power automate 🗡

**Comment by NiklasJegg1** [comment]
@MartinPankraz  another thing to consider: if you use the SAP OData Connector you also need to add the user_impersonation Scope of your Enterprise Application handling the oAuth Tokens to the App registration for the Middle Tier.
Otherwise you will still get 401 with Power Automate

**Comment by MartinPankraz** [comment]
Is that missing from the blog?

**Comment by NiklasJegg1** [comment]
@MartinPankraz  i am not 100% sure at the top of my head but i found out about in the Holger´s Video:https://www.youtube.com/watch?v=NSE--fVLdUg&list=PLvqyDwoCkBXYHECuHw2pKN2DrWjyn3q5f&index=14&ab_channel=SAPonAzure

**Comment by NiklasJegg1** [comment]
@sweiDl just so i can understand : your System works with SAP Logon Gui (with SSO) Sap Fiori with SSO and the Connector ? With the same Netweaver Application? 

I am really struggling to get this to work. For me it works partly with 2 separate netweaver apps in azure but not with one. 
Would you be so kind to provide me with some screenshots for your config in sap/Azure?

Thanks a Lot. Niklas

**Comment by MartinPankraz** [comment]
Hey @NiklasJegg1,

did you check the screenshots above from @sweiDl? Also I added one from my internal RnD setup to the blog [here](https://community.sap.com/t5/enterprise-resource-planning-blogs-by-members/integrating-low-code-solutions-with-microsoft-using-sap-integration-suite/ba-p/13789298). ACS change should not be required though.

Cheers Martin

**Comment by NiklasJegg1** [comment]
Hi @MartinPankraz yes but i can´t wrap my head around this -- i think something is not configured correctly in SAP which i am not a pro im just an IT guy :D

<img width="803" height="354" alt="Image" src="https://github.com/user-attachments/assets/3c296685-f6db-4a85-bbc9-f9655813f313" />

<img width="1048" height="105" alt="Image" src="https://github.com/user-attachments/assets/c415a817-d69b-4250-8e0e-c9bdf4dab666" />

<img width="1463" height="155" alt="Image" src="https://github.com/user-attachments/assets/a44741c3-2d47-4f12-9dcb-5fad5197eddd" />

<img width="813" height="69" alt="Image" src="https://github.com/user-attachments/assets/30d93293-d30f-4e4f-8e14-85005db00783" />

<img width="692" height="106" alt="Image" src="https://github.com/user-attachments/assets/c18c2b94-895b-4ff7-a411-bc77b05c0c77" />

**Comment by MartinPankraz** [comment]
The error message indicates that the SAML assertion generated by Entra ID is having the saml url as recipient rather than oauth. That issue originates from your token request rather than SAP. Try to repopulate the settings on Entra. Swapping the default to oauth will likely break your SAML for web UIs.

**Comment by NiklasJegg1** [comment]
@MartinPankraz exactly if i swap the default i get this error which is related to the name format in the request. 
if i switch it to userprincipalname it works for Oauth but for saml Fiori not because no user is found :) the mapping in our backend is the issue there.

<img width="726" height="165" alt="Image" src="https://github.com/user-attachments/assets/6db51c7a-750e-41d8-a66a-03ae924fa86e" />

<img width="1474" height="240" alt="Image" src="https://github.com/user-attachments/assets/e02d31aa-0723-4570-8cb2-447096619346" />

**Comment by MartinPankraz** [comment]
Looks like more intensive integration work between you and your SAP team is required to find the correct config across all parties.

**Comment by NiklasJegg1** [comment]
@MartinPankraz  okay i got it to work now with APIM too :D

<img width="791" height="215" alt="Image" src="https://github.com/user-attachments/assets/3df1d388-6d54-4483-979c-d26b4817353e" />

I have adjusted the ACS Url. 
and in the SAP SAML2 Transaction i just added EMail as Another Name ID Format.

Now SAG Logon works with SSO + SAP Fiori and OAuth flow for APIM

**Comment by MartinPankraz** [comment]
Nice @NiklasJegg1!

Email name id was definitely missing. What did you provide as ACS Url for future reference for others encountering the issue?

**Comment by NiklasJegg1** [comment]
@MartinPankraz just standard values hahaha 

<img width="663" height="154" alt="Image" src="https://github.com/user-attachments/assets/f3e9ace5-155a-409f-94a7-da3683697ef1" />

<img width="1133" height="436" alt="Image" src="https://github.com/user-attachments/assets/74fe1ae8-d922-4cdf-999b-3e5629e16985" />
